version: '3.9'
name: todo
services:
  about-me:
    image: todo
    container_name: todo
    restart: always                     # 重启策略: 容器退出时总是重启容器
    build:
      context: ../                       # 指定设定上下文根目录，然后以该目录为准指定Dockerfile
      dockerfile: docker/Dockerfile
    environment:
      TZ: Asia/Shanghai
    ports:
      - "8084:3000"
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro"